using System.Collections.Generic;
using ColossalFramework.Globalization;
using UnityEngine;

namespace FavoriteCims
{
	public class FavCimsLang : MonoBehaviour
	{
        public static string GameLanguage;

        public static Dictionary<string, string> it = [];

        public static Dictionary<string, string> en = [];

        public static Dictionary<string, string> nl = [];

        public static Dictionary<string, string> rus = [];

        public static string Text(string index)
		{
			bool flag = FavCimsLang.GameLanguage == null || FavCimsLang.GameLanguage != Locale.Get("LANGUAGE_ENGLISH");
			if (flag)
			{
				try
				{
					FavCimsLang.GameLanguage = Locale.Get("LANGUAGE_ENGLISH");
					bool flag2 = FavCimsLang.GameLanguage == "(ITALIAN)";
					if (flag2)
					{
						FavCimsLang.it = new Dictionary<string, string>();
						FavCimsLang.it["FavCimsButton_tooltip"] = "I Miei Cims Preferiti";
						FavCimsLang.it["FavCimsBCMenuButton_text"] = "Abitanti";
						FavCimsLang.it["FavCimsBCMenuButton_tooltip"] = "Persone che segui";
						FavCimsLang.it["FavCimsBBMenuButton_text"] = "Edifici";
						FavCimsLang.it["FavCimsBBMenuButton_tooltip"] = "Edifici Preferiti";
						FavCimsLang.it["FavCimsBSMenuButton_text"] = "Stats";
						FavCimsLang.it["FavCimsBSMenuButton_tooltip"] = "Info e Statistiche";
						FavCimsLang.it["FavStarButton_enable_tooltip"] = "Clicca per aggiungere ai preferiti!";
						FavCimsLang.it["FavStarButton_disable_tooltip"] = "Clicca per rimuovere dai preferiti :(";
						FavCimsLang.it["FavCimsHappinesColText_text"] = "Stato";
						FavCimsLang.it["FavCimsHappinesColText_tooltip"] = "Felicita' cittadino";
						FavCimsLang.it["FavCimsNameColText_text"] = "Nome Abitante";
						FavCimsLang.it["FavCimsNameColText_tooltip"] = "Nome del Cittadino";
						FavCimsLang.it["FavCimsEduColText_text"] = "Istruzione";
						FavCimsLang.it["FavCimsEduColText_tooltip"] = "Livello di educazione del Cittadino";
						FavCimsLang.it["FavCimsWorkingPlaceColText_text"] = "Posto di Lavoro / Studio";
						FavCimsLang.it["FavCimsWorkingPlaceColText_tooltip"] = "Edificio in cui lavora o studia il Cittadino";
						FavCimsLang.it["FavCimsAgePhaseColText_text"] = "Fase di vita";
						FavCimsLang.it["FavCimsAgePhaseColText_tooltip"] = "Fase della vita in cui si trova il cittadino";
						FavCimsLang.it["FavCimsAgeColText_text"] = "Eta'";
						FavCimsLang.it["FavCimsAgeColText_tooltip"] = "L'Eta' del Cittadino";
						FavCimsLang.it["FavCimsHomeColText_text"] = "Abitazione";
						FavCimsLang.it["FavCimsHomeColText_tooltip"] = "Il cittadino abita in questa casa";
						FavCimsLang.it["FavCimsLastActColText_text"] = "Ultima Attivita'";
						FavCimsLang.it["FavCimsLastActColText_tooltip"] = "Quello che sta' facendo il cittadino in questo momento";
						FavCimsLang.it["FavCimsCloseButtonCol_text"] = "Chiudi";
						FavCimsLang.it["FavCimsCloseButtonCol_tooltip"] = "Clicca sul pulsante chiudi per rimuovere il cittadino dai preferiti :(";
						FavCimsLang.it["Male"] = "Maschio";
						FavCimsLang.it["Female"] = "Femmina";
						FavCimsLang.it["AgePhase_Child_Male"] = "Bambino";
						FavCimsLang.it["AgePhase_Teen_Male"] = "Ragazzino";
						FavCimsLang.it["AgePhase_Young_Male"] = "Ragazzo";
						FavCimsLang.it["AgePhase_Adult_Male"] = "Adulto";
						FavCimsLang.it["AgePhase_Senior_Male"] = "Anziano";
						FavCimsLang.it["Education_Uneducated_Male"] = "Non Istruito";
						FavCimsLang.it["Education_OneSchool_Male"] = "Istruito";
						FavCimsLang.it["Education_TwoSchools_Male"] = "Ben Istruito";
						FavCimsLang.it["Education_ThreeSchools_Male"] = "Molto Istruito";
						FavCimsLang.it["AgePhase_Child_Female"] = "Bambina";
						FavCimsLang.it["AgePhase_Teen_Female"] = "Ragazzina";
						FavCimsLang.it["AgePhase_Young_Female"] = "Ragazza";
						FavCimsLang.it["AgePhase_Adult_Female"] = "Adulta";
						FavCimsLang.it["AgePhase_Senior_Female"] = "Anziana";
						FavCimsLang.it["Education_Uneducated_Female"] = "Non Istruita";
						FavCimsLang.it["Education_OneSchool_Female"] = "Istruita";
						FavCimsLang.it["Education_TwoSchools_Female"] = "Ben Istruita";
						FavCimsLang.it["Education_ThreeSchools_Female"] = "Molto Istruita";
						FavCimsLang.it["AgePhaseDead_Male"] = "Morto";
						FavCimsLang.it["AgePhaseDead_Female"] = "Morta";
						FavCimsLang.it["People_Life_Status_Alive"] = "Il Cittadino e' vivo";
						FavCimsLang.it["People_Life_Status_Dead"] = "Il Cittadino e' morto";
						FavCimsLang.it["People_Life_Status_Dead_date"] = "il giorno";
						FavCimsLang.it["People_Life_Status_Dead_time"] = "alle ore";
						FavCimsLang.it["NotificationIconVeryUnhappy"] = "Molto Infelice";
						FavCimsLang.it["NotificationIconUnhappy"] = "Infelice";
						FavCimsLang.it["NotificationIconHappy"] = "Felice";
						FavCimsLang.it["NotificationIconVeryHappy"] = "Veramente Felice";
						FavCimsLang.it["NotificationIconExtremelyHappy"] = "Estremamente Felice";
						FavCimsLang.it["time_format"] = "dd-mm-yyyy";
						FavCimsLang.it["People_Life_Status_IsGone"] = "Questo cittadino ha abbandonato la citta'";
						FavCimsLang.it["Citizen_HomeLess"] = "Senzatetto";
						FavCimsLang.it["Citizen_HomeLess_tooltip"] = "Questo cittadino non ha una casa";
						FavCimsLang.it["HomeOutsideTheCity"] = "Molto molto lontano";
						FavCimsLang.it["Home_Location_Dead"] = "Al Cimitero";
						FavCimsLang.it["Citizen_Retired"] = "In Pensione";
						FavCimsLang.it["Citizen_Retired_tooltip"] = "Il cittadino si e' ritirato dal lavoro";
						FavCimsLang.it["Unemployed_tooltip"] = "Il cittadino ha motlo tempo libero al momento...";
						FavCimsLang.it["Government_job"] = "Edificio governativo";
						FavCimsLang.it["Electricity_job"] = "Centrale Elettrica";
						FavCimsLang.it["Water_job"] = "Centrale Idrica";
						FavCimsLang.it["Generic_job_place"] = "Il cittadino lavora in questo edificio";
						FavCimsLang.it["Vehicle_on_foot"] = "Il cittadino sta camminando";
						FavCimsLang.it["Citizen_Details"] = "Dettagli del cittadino";
						FavCimsLang.it["Citizen_Details_fullTemplate"] = "Troppe finestre dettagli aperte, chiudine una prima di aprirne una nuova";
						FavCimsLang.it["Status_static_label"] = "Stato : ";
						FavCimsLang.it["Citizen_Family_unit"] = "Famiglia";
						FavCimsLang.it["NowInThisDistrict"] = "Attualmente si trova nel distretto: ";
						FavCimsLang.it["DistrictLabel"] = "Distretto: ";
						FavCimsLang.it["DistrictNameNoDistrict"] = "Nessuno";
						FavCimsLang.it["Citizen_Details_No_Partner"] = "Nessun Partner";
						FavCimsLang.it["Citizen_Details_No_Childs"] = "Nessun Figlio";
						FavCimsLang.it["Right_click_to_swith_tooltip"] = "Tasto destro per invertire";
						FavCimsLang.it["Home_Bubble_panel_Label"] = "Casa : ";
						FavCimsLang.it["Low_Wealth_Male"] = "Povero";
						FavCimsLang.it["Mid_Wealth_Male"] = "Benestante";
						FavCimsLang.it["High_Wealth_Male"] = "Ricco";
						FavCimsLang.it["Low_Wealth_Female"] = "Povera";
						FavCimsLang.it["Mid_Wealth_Female"] = "Benestante";
						FavCimsLang.it["High_Wealth_Female"] = "Ricca";
						FavCimsLang.it["WellBeingLabel"] = "Benessere: ";
						FavCimsLang.it["HappinessLabel"] = "Felicita' complessiva: ";
						FavCimsLang.it["Wealth_Label"] = "Ricchezza";
						FavCimsLang.it["Health_Level_VerySick_Male"] = "Molto malato";
						FavCimsLang.it["Health_Level_Sick_Male"] = "Malato";
						FavCimsLang.it["Health_Level_PoorHealth_Male"] = "Salute scarsa";
						FavCimsLang.it["Health_Level_Healthy_Male"] = "In salute";
						FavCimsLang.it["Health_Level_VeryHealthy_Male"] = "Buona salute";
						FavCimsLang.it["Health_Level_ExcellentHealth_Male"] = "Ottima salute";
						FavCimsLang.it["Health_Level_VerySick_Female"] = "Molto malata";
						FavCimsLang.it["Health_Level_Sick_Female"] = "Malata";
						FavCimsLang.it["Health_Level_PoorHealth_Female"] = "Salute scarsa";
						FavCimsLang.it["Health_Level_Healthy_Female"] = "In salute";
						FavCimsLang.it["Health_Level_VeryHealthy_Female"] = "Buona salute";
						FavCimsLang.it["Health_Level_ExcellentHealth_Female"] = "Ottima salute";
						FavCimsLang.it["District_Label"] = "Distretto: ";
						FavCimsLang.it["District_Label_tooltip"] = "Attualmente si trova in questo distretto";
						FavCimsLang.it["Citizen_Details_NoUnit"] = "Il cittadino e' morto o non ha una casa";
						FavCimsLang.it["Citizen_wait_hearse"] = "Aspetta il carro funebre";
						FavCimsLang.it["Citizen_on_hearse"] = "Sul carro funebre";
						FavCimsLang.it["Citizen_hisfuneral"] = "Cerimonia funebre";
						FavCimsLang.it["Citizen_buried"] = "Sepolto";
						FavCimsLang.it["Citizen_Tourist_tooltip"] = "Questo cittadino e' in visita nella nostra citta'";
						FavCimsLang.it["View_PassengersList"] = "Guarda lista passeggeri";
						FavCimsLang.it["View_NoPassengers"] = "Nessun passeggero";
						FavCimsLang.it["Vehicle_Passengers"] = "Passeggeri nel veicolo";
						FavCimsLang.it["Vehicle_DriverIconText"] = "Al volante";
						FavCimsLang.it["Vehicle_PasssengerIconText"] = "Passeggeri";
						FavCimsLang.it["Citizens_HouseHolds"] = "Guarda Inquilini";
						FavCimsLang.it["Citizens_HouseHoldsTitle"] = "Inquilini";
						FavCimsLang.it["CitizenOnBuilding"] = "Lista Dipendenti e Visitatori";
						FavCimsLang.it["CitizenOnBuildingTitle"] = "Dipendenti e Visitatori";
						FavCimsLang.it["OnBuilding_Residential"] = "Appartamento ";
						FavCimsLang.it["View_List"] = "Guarda ";
						FavCimsLang.it["OnBuilding_Guests"] = "Visitatori";
						FavCimsLang.it["OnBuilding_Workers"] = "Dipendenti al lavoro";
						FavCimsLang.it["WorkersOnBuilding"] = "Lavoratori nell'edificio";
						FavCimsLang.it["OnBuilding_NoWorkers"] = "Nessuno lavora oggi";
						FavCimsLang.it["OnBuilding_NoGuests"] = "Nessun visitatore";
						FavCimsLang.it["BuildingIsEmpty"] = "Nessuno vive o lavora in questo edificio";
						FavCimsLang.it["OnBuilding_TotalWorkers"] = "Totale :";
						FavCimsLang.it["Buildings_Type_CommercialEco"] = "Edificio Commerciale Ecologico";
						FavCimsLang.it["Buildings_Type_CommercialLeisure"] = "Edificio Commerciale d'intrattenimento.";
						FavCimsLang.it["Buildings_Type_CommercialTourist"] = "Edificio Turistico o adibito al turismo.";
						FavCimsLang.it["Citizen_Arrested"] = "Questo cittadino e' in prigione!";
						FavCimsLang.it["Transported_to_Prison"] = "Scortato in Prigione!";
						FavCimsLang.it["Jailed_into"] = "Incarcerato presso ";
						FavCimsLang.it["Citizen_Under_Arrest"] = "Cittadini in arresto";
						FavCimsLang.it["OnBuilding_noArrested"] = "Nessun cittadino in arresto";
						FavCimsLang.it["OnPolice_Building_Service"] = "Secondini e Carcerati";
						FavCimsLang.it["OnEducation_Building_Service"] = "Insegnanti e Studenti";
						FavCimsLang.it["OnMedical_Building_Service"] = "Medici e Pazienti";
						FavCimsLang.it["Citizen_at_School"] = "Studenti a lezione";
						FavCimsLang.it["Citizen_on_Clinic"] = "Pazienti in cura";
						return FavCimsLang.it[index];
					}
					bool flag3 = FavCimsLang.GameLanguage == "(DUTCH)";
					if (flag3)
					{
						FavCimsLang.nl = new Dictionary<string, string>();
						FavCimsLang.nl["FavCimsButton_tooltip"] = "Mijn favoriete cims";
						FavCimsLang.nl["FavCimsBCMenuButton_text"] = "Inwoners";
						FavCimsLang.nl["FavCimsBCMenuButton_tooltip"] = "Gevolgde personen";
						FavCimsLang.nl["FavCimsBBMenuButton_text"] = "Gebouwen";
						FavCimsLang.nl["FavCimsBBMenuButton_tooltip"] = "Favoriete gebouwen";
						FavCimsLang.nl["FavCimsBSMenuButton_text"] = "Stats";
						FavCimsLang.nl["FavCimsBSMenuButton_tooltip"] = "Info en stats";
						FavCimsLang.nl["FavStarButton_enable_tooltip"] = "Klik hier om aan favorieten toe te voegen!";
						FavCimsLang.nl["FavStarButton_disable_tooltip"] = "Klik hier om uit favoriete te verwijderen :(";
						FavCimsLang.nl["FavCimsHappinesColText_text"] = "Status";
						FavCimsLang.nl["FavCimsHappinesColText_tooltip"] = "Inwonergeluk";
						FavCimsLang.nl["FavCimsNameColText_text"] = "Inwonernaam";
						FavCimsLang.nl["FavCimsNameColText_tooltip"] = "Inwonernaam";
						FavCimsLang.nl["FavCimsEduColText_text"] = "Opleiding";
						FavCimsLang.nl["FavCimsEduColText_tooltip"] = "Opleidingsniveau van de inwoner";
						FavCimsLang.nl["FavCimsWorkingPlaceColText_text"] = "Beroep";
						FavCimsLang.nl["FavCimsWorkingPlaceColText_tooltip"] = "Plaats waar de inwoner werkt of onderwijs geniet";
						FavCimsLang.nl["FavCimsAgePhaseColText_text"] = "Levensfase";
						FavCimsLang.nl["FavCimsAgePhaseColText_tooltip"] = "Levensfase van de inwoner";
						FavCimsLang.nl["FavCimsAgeColText_text"] = "Leeftijd";
						FavCimsLang.nl["FavCimsAgeColText_tooltip"] = "Leeftijf van de inwoner";
						FavCimsLang.nl["FavCimsHomeColText_text"] = "Woning van inwoner";
						FavCimsLang.nl["FavCimsHomeColText_tooltip"] = "Inwoner woont in dit huis";
						FavCimsLang.nl["FavCimsLastActColText_text"] = "Laatste activiteit";
						FavCimsLang.nl["FavCimsLastActColText_tooltip"] = "Wat de inwoner op dit moment aan het doen is";
						FavCimsLang.nl["FavCimsCloseButtonCol_text"] = "Sluiten";
						FavCimsLang.nl["FavCimsCloseButtonCol_tooltip"] = "Klik op de knop \"Sluiten\" om de inwoner uit de favorieten te verwijderen :(";
						FavCimsLang.nl["Male"] = "Mannelijk";
						FavCimsLang.nl["Female"] = "Vrouwelijk";
						FavCimsLang.nl["AgePhase_Child_Male"] = "Jongetje";
						FavCimsLang.nl["AgePhase_Teen_Male"] = "Jongen";
						FavCimsLang.nl["AgePhase_Young_Male"] = "Jonge man";
						FavCimsLang.nl["AgePhase_Adult_Male"] = "Man";
						FavCimsLang.nl["AgePhase_Senior_Male"] = "Oude man";
						FavCimsLang.nl["Education_Uneducated_Male"] = "Ongeschoold";
						FavCimsLang.nl["Education_OneSchool_Male"] = "Laag geschoold";
						FavCimsLang.nl["Education_TwoSchools_Male"] = "Goed geschoold";
						FavCimsLang.nl["Education_ThreeSchools_Male"] = "Hoog opgeleid";
						FavCimsLang.nl["AgePhase_Child_Female"] = "Meisje";
						FavCimsLang.nl["AgePhase_Teen_Female"] = "Meid";
						FavCimsLang.nl["AgePhase_Young_Female"] = "Jonge vrouw";
						FavCimsLang.nl["AgePhase_Adult_Female"] = "Vrouw";
						FavCimsLang.nl["AgePhase_Senior_Female"] = "Oude vrouw";
						FavCimsLang.nl["Education_Uneducated_Female"] = "Ongeschoold";
						FavCimsLang.nl["Education_OneSchool_Female"] = "Laag geschoold";
						FavCimsLang.nl["Education_TwoSchools_Female"] = "Goed geschoold";
						FavCimsLang.nl["Education_ThreeSchools_Female"] = "Hoog opgeleid";
						FavCimsLang.nl["AgePhaseDead_Male"] = "Dood";
						FavCimsLang.nl["AgePhaseDead_Female"] = "Dood";
						FavCimsLang.nl["People_Life_Status_Alive"] = "Inwoner leeft";
						FavCimsLang.nl["People_Life_Status_Dead"] = "Inwoner is dood";
						FavCimsLang.nl["People_Life_Status_Dead_date"] = "op deze datum";
						FavCimsLang.nl["People_Life_Status_Dead_time"] = "om";
						FavCimsLang.nl["NotificationIconVeryUnhappy"] = "Zeer ongelukkig";
						FavCimsLang.nl["NotificationIconUnhappy"] = "Ongelukkig";
						FavCimsLang.nl["NotificationIconHappy"] = "Gelukkig";
						FavCimsLang.nl["NotificationIconVeryHappy"] = "Zeer gelukkig";
						FavCimsLang.nl["NotificationIconExtremelyHappy"] = "Buitengewoon gelukkig";
						FavCimsLang.nl["time_format"] = "mm-dd-yyyy";
						FavCimsLang.nl["People_Life_Status_IsGone"] = "Inwoner is momenteel niet in de stad";
						FavCimsLang.nl["Citizen_HomeLess"] = "Dakloos";
						FavCimsLang.nl["Citizen_HomeLess_tooltip"] = "Inwoner heeft geen woning";
						FavCimsLang.nl["HomeOutsideTheCity"] = "Erg ver weg";
						FavCimsLang.nl["Home_Location_Dead"] = "Op de begraafplaats";
						FavCimsLang.nl["Citizen_Retired"] = "Gepensioneerd";
						FavCimsLang.nl["Citizen_Retired_tooltip"] = "Inwoner is met pensioen";
						FavCimsLang.nl["Unemployed_tooltip"] = "Inwoner heeft momenteel veel vrije tijd...";
						FavCimsLang.nl["Government_job"] = "Overheidsgebouw";
						FavCimsLang.nl["Electricity_job"] = "Electriciteitscentrale";
						FavCimsLang.nl["Water_job"] = "Waterbedrijf";
						FavCimsLang.nl["Generic_job_place"] = "Inwoner werkt in dit gebouw";
						FavCimsLang.nl["Vehicle_on_foot"] = "Inwoner is te voet";
						FavCimsLang.nl["Citizen_Details"] = "Inwonerdetails";
						FavCimsLang.nl["Citizen_Details_fullTemplate"] = "Teveel gezinvensters geopend, sluit er alvorens andere te openen";
						FavCimsLang.nl["Status_static_label"] = "Status: ";
						FavCimsLang.nl["Citizen_Family_unit"] = "Gezin";
						FavCimsLang.nl["NowInThisDistrict"] = "Is op dit moment in de wijk: ";
						FavCimsLang.nl["DistrictLabel"] = "Wijk: ";
						FavCimsLang.nl["DistrictNameNoDistrict"] = "Geen";
						FavCimsLang.nl["Citizen_Details_No_Partner"] = "Geen partner";
						FavCimsLang.nl["Citizen_Details_No_Childs"] = "Geen kinderen";
						FavCimsLang.nl["Right_click_to_swith_tooltip"] = "Rechtermuisknop om van inwoner te wisselen";
						FavCimsLang.nl["Home_Bubble_panel_Label"] = "Woning: ";
						FavCimsLang.nl["Low_Wealth_Male"] = "Arm";
						FavCimsLang.nl["Mid_Wealth_Male"] = "Modaal";
						FavCimsLang.nl["High_Wealth_Male"] = "Rijk";
						FavCimsLang.nl["Low_Wealth_Female"] = "Arm";
						FavCimsLang.nl["Mid_Wealth_Female"] = "Modaal";
						FavCimsLang.nl["High_Wealth_Female"] = "Rijk";
						FavCimsLang.nl["WellBeingLabel"] = "Welzijn: ";
						FavCimsLang.nl["HappinessLabel"] = "Geluk: ";
						FavCimsLang.nl["Wealth_Label"] = "Rijkdom";
						FavCimsLang.nl["Health_Level_VerySick_Male"] = "Zeer ziek";
						FavCimsLang.nl["Health_Level_Sick_Male"] = "Ziek";
						FavCimsLang.nl["Health_Level_PoorHealth_Male"] = "Zwakke gezondheid";
						FavCimsLang.nl["Health_Level_Healthy_Male"] = "Normale gezondheid";
						FavCimsLang.nl["Health_Level_VeryHealthy_Male"] = "Goede gezondheid";
						FavCimsLang.nl["Health_Level_ExcellentHealth_Male"] = "Uitmuntende gezondheid";
						FavCimsLang.nl["Health_Level_VerySick_Female"] = "Zeer ziek";
						FavCimsLang.nl["Health_Level_Sick_Female"] = "Ziek";
						FavCimsLang.nl["Health_Level_PoorHealth_Female"] = "Zwakke gezondheid";
						FavCimsLang.nl["Health_Level_Healthy_Female"] = "Normale gezondheid";
						FavCimsLang.nl["Health_Level_VeryHealthy_Female"] = "Goede gezondheid";
						FavCimsLang.nl["Health_Level_ExcellentHealth_Female"] = "Uitmuntende gezondheid";
						FavCimsLang.nl["District_Label"] = "Wijk: ";
						FavCimsLang.nl["District_Label_tooltip"] = "Momenteel in de wijk";
						FavCimsLang.nl["Citizen_Details_NoUnit"] = "Inwoner is dood of dakloos";
						FavCimsLang.nl["Citizen_wait_hearse"] = "Wacht op een lijkwagen";
						FavCimsLang.nl["Citizen_on_hearse"] = "In lijkwagen";
						FavCimsLang.nl["Citizen_hisfuneral"] = "Begravenisceremonie";
						FavCimsLang.nl["Citizen_buried"] = "Onder de groene zoden";
						FavCimsLang.nl["Citizen_Tourist_tooltip"] = "This citizen is visiting our City";
						FavCimsLang.nl["View_PassengersList"] = "View passengers list";
						FavCimsLang.nl["View_NoPassengers"] = "No passengers";
						FavCimsLang.nl["Vehicle_Passengers"] = "Passengers on board";
						FavCimsLang.nl["Vehicle_DriverIconText"] = "Vehicle Driver";
						FavCimsLang.nl["Vehicle_PasssengerIconText"] = "Passengers";
						FavCimsLang.nl["Citizens_HouseHolds"] = "View Residents";
						FavCimsLang.nl["Citizens_HouseHoldsTitle"] = "Residents";
						FavCimsLang.nl["CitizenOnBuilding"] = "Employees and Guests List";
						FavCimsLang.nl["CitizenOnBuildingTitle"] = "Employees and Guests";
						FavCimsLang.nl["OnBuilding_Residential"] = "Apartment ";
						FavCimsLang.nl["View_List"] = "View ";
						FavCimsLang.nl["OnBuilding_Guests"] = "Guests";
						FavCimsLang.nl["OnBuilding_Workers"] = "Employees at work";
						FavCimsLang.nl["WorkersOnBuilding"] = "List of employees at work";
						FavCimsLang.nl["OnBuilding_NoWorkers"] = "Nobody at work now";
						FavCimsLang.nl["OnBuilding_NoGuests"] = "No guests inside";
						FavCimsLang.nl["BuildingIsEmpty"] = "Nobody works or lives here";
						FavCimsLang.nl["OnBuilding_TotalWorkers"] = "Total :";
						FavCimsLang.nl["Buildings_Type_CommercialEco"] = "Ecologic Commercial Building";
						FavCimsLang.nl["Buildings_Type_CommercialLeisure"] = "Leisure Commercial Building";
						FavCimsLang.nl["Buildings_Type_CommercialTourist"] = "Tourism Commercial Building";
						FavCimsLang.nl["Citizen_Arrested"] = "This Citizen is in Jail!";
						FavCimsLang.nl["Transported_to_Prison"] = "Transported to Prison";
						FavCimsLang.nl["Jailed_into"] = "Jailed into ";
						FavCimsLang.nl["Citizen_Under_Arrest"] = "Citizens under arrest";
						FavCimsLang.nl["OnBuilding_noArrested"] = "Nobody jailed here";
						FavCimsLang.nl["OnPolice_Building_Service"] = "Guards and Prisoners";
						FavCimsLang.nl["OnEducation_Building_Service"] = "Teachers and Students";
						FavCimsLang.nl["OnMedical_Building_Service"] = "Doctors and Patients";
						FavCimsLang.nl["Citizen_at_School"] = "Students at school";
						FavCimsLang.nl["Citizen_on_Clinic"] = "Patients being treated";
						return FavCimsLang.nl[index];
					}
					bool flag4 = FavCimsLang.GameLanguage == "(RUSSIAN)";
					if (flag4)
					{
						FavCimsLang.rus = new Dictionary<string, string>();
						FavCimsLang.rus["FavCimsButton_tooltip"] = "My Favorite Cims";
						FavCimsLang.rus["FavCimsBCMenuButton_text"] = "Жители";
						FavCimsLang.rus["FavCimsBCMenuButton_tooltip"] = "Люди";
						FavCimsLang.rus["FavCimsBBMenuButton_text"] = "Здания";
						FavCimsLang.rus["FavCimsBBMenuButton_tooltip"] = "Избранные здания";
						FavCimsLang.rus["FavCimsBSMenuButton_text"] = "Показатели";
						FavCimsLang.rus["FavCimsBSMenuButton_tooltip"] = "Инфо и показатели";
						FavCimsLang.rus["FavStarButton_enable_tooltip"] = "Кликни, чтобы добавить в Избранные!";
						FavCimsLang.rus["FavStarButton_disable_tooltip"] = "Кликни, чтобы удалить из Избранных :(";
						FavCimsLang.rus["FavCimsHappinesColText_text"] = "Статус";
						FavCimsLang.rus["FavCimsHappinesColText_tooltip"] = "Статус счастья";
						FavCimsLang.rus["FavCimsNameColText_text"] = "Имя жителя";
						FavCimsLang.rus["FavCimsNameColText_tooltip"] = "Имя жителя";
						FavCimsLang.rus["FavCimsEduColText_text"] = "Образование";
						FavCimsLang.rus["FavCimsEduColText_tooltip"] = "Уровень образования";
						FavCimsLang.rus["FavCimsWorkingPlaceColText_text"] = "Место учебы/работы";
						FavCimsLang.rus["FavCimsWorkingPlaceColText_tooltip"] = "Место где учится/работает житель";
						FavCimsLang.rus["FavCimsAgePhaseColText_text"] = "Возрастная категория";
						FavCimsLang.rus["FavCimsAgePhaseColText_tooltip"] = "Категория возраста жителя";
						FavCimsLang.rus["FavCimsAgeColText_text"] = "Возраст";
						FavCimsLang.rus["FavCimsAgeColText_tooltip"] = "Возраст жителя";
						FavCimsLang.rus["FavCimsHomeColText_text"] = "Место жительства";
						FavCimsLang.rus["FavCimsHomeColText_tooltip"] = "Горожанин живет здесь";
						FavCimsLang.rus["FavCimsLastActColText_text"] = "Последняя активность";
						FavCimsLang.rus["FavCimsLastActColText_tooltip"] = "Чем житель занят в данный момент";
						FavCimsLang.rus["FavCimsCloseButtonCol_text"] = "Закрыть";
						FavCimsLang.rus["FavCimsCloseButtonCol_tooltip"] = "Нажми Закрыть, чтобы убрать жителя из Избранных :(";
						FavCimsLang.rus["Male"] = "Мужчина";
						FavCimsLang.rus["Female"] = "Женщина";
						FavCimsLang.rus["AgePhase_Child_Male"] = "Ребенок";
						FavCimsLang.rus["AgePhase_Teen_Male"] = "Подросток";
						FavCimsLang.rus["AgePhase_Young_Male"] = "Молодой";
						FavCimsLang.rus["AgePhase_Adult_Male"] = "Взрослый";
						FavCimsLang.rus["AgePhase_Senior_Male"] = "Старый";
						FavCimsLang.rus["Education_Uneducated_Male"] = "Необразован";
						FavCimsLang.rus["Education_OneSchool_Male"] = "Начальная школа";
						FavCimsLang.rus["Education_TwoSchools_Male"] = "Средняя школа";
						FavCimsLang.rus["Education_ThreeSchools_Male"] = "Университет";
						FavCimsLang.rus["AgePhase_Child_Female"] = "Ребенок";
						FavCimsLang.rus["AgePhase_Teen_Female"] = "Подросток";
						FavCimsLang.rus["AgePhase_Young_Female"] = "Молодая";
						FavCimsLang.rus["AgePhase_Adult_Female"] = "Взрослая";
						FavCimsLang.rus["AgePhase_Senior_Female"] = "Старая";
						FavCimsLang.rus["Education_Uneducated_Female"] = "Необразована";
						FavCimsLang.rus["Education_OneSchool_Female"] = "Начальная школа";
						FavCimsLang.rus["Education_TwoSchools_Female"] = "Средняя школа";
						FavCimsLang.rus["Education_ThreeSchools_Female"] = "Университет";
						FavCimsLang.rus["AgePhaseDead_Male"] = "Умер";
						FavCimsLang.rus["AgePhaseDead_Female"] = "Умерла";
						FavCimsLang.rus["People_Life_Status_Alive"] = "Горожанин жив";
						FavCimsLang.rus["People_Life_Status_Dead"] = "Горожанин умер";
						FavCimsLang.rus["People_Life_Status_Dead_date"] = "в этот день";
						FavCimsLang.rus["People_Life_Status_Dead_time"] = "в это время";
						FavCimsLang.rus["NotificationIconVeryUnhappy"] = "Горемыка";
						FavCimsLang.rus["NotificationIconUnhappy"] = "Грустный(ая)";
						FavCimsLang.rus["NotificationIconHappy"] = "Радостный(ая)";
						FavCimsLang.rus["NotificationIconVeryHappy"] = "Счастливец(а)";
						FavCimsLang.rus["NotificationIconExtremelyHappy"] = "На седьмом небе";
						FavCimsLang.rus["time_format"] = "мм-дд-гггг";
						FavCimsLang.rus["People_Life_Status_IsGone"] = "Житель уехал из города";
						FavCimsLang.rus["Citizen_HomeLess"] = "Бомж";
						FavCimsLang.rus["Citizen_HomeLess_tooltip"] = "У жителя нет дома";
						FavCimsLang.rus["HomeOutsideTheCity"] = "Далеко-далеко";
						FavCimsLang.rus["Home_Location_Dead"] = "На кладбище";
						FavCimsLang.rus["Citizen_Retired"] = "Не работает";
						FavCimsLang.rus["Citizen_Retired_tooltip"] = "Житель больше не работает";
						FavCimsLang.rus["Unemployed_tooltip"] = "У жителя полно свободного времени...";
						FavCimsLang.rus["Government_job"] = "Административное Здание";
						FavCimsLang.rus["Electricity_job"] = "Электростанция";
						FavCimsLang.rus["Water_job"] = "Гидростанция";
						FavCimsLang.rus["Generic_job_place"] = "Житель работает здесь";
						FavCimsLang.rus["Vehicle_on_foot"] = "Житель идет пешком";
						FavCimsLang.rus["Citizen_Details"] = "Подробности";
						FavCimsLang.rus["Citizen_Details_fullTemplate"] = "Открыто слишком много Панелей Семей";
						FavCimsLang.rus["Status_static_label"] = "Статус : ";
						FavCimsLang.rus["Citizen_Family_unit"] = "Семья";
						FavCimsLang.rus["NowInThisDistrict"] = "Находится в районе: ";
						FavCimsLang.rus["DistrictLabel"] = "Район: ";
						FavCimsLang.rus["DistrictNameNoDistrict"] = "Отсутсвует";
						FavCimsLang.rus["Citizen_Details_No_Partner"] = "Одинок(а)";
						FavCimsLang.rus["Citizen_Details_No_Childs"] = "Детей нет";
						FavCimsLang.rus["Right_click_to_swith_tooltip"] = "Правая кнопка - сменить жителя";
						FavCimsLang.rus["Home_Bubble_panel_Label"] = "Дом : ";
						FavCimsLang.rus["Low_Wealth_Male"] = "Бедный";
						FavCimsLang.rus["Mid_Wealth_Male"] = "Обеспеченный";
						FavCimsLang.rus["High_Wealth_Male"] = "Богатый";
						FavCimsLang.rus["Low_Wealth_Female"] = "Бедная";
						FavCimsLang.rus["Mid_Wealth_Female"] = "Обеспеченная";
						FavCimsLang.rus["High_Wealth_Female"] = "Богатая";
						FavCimsLang.rus["WellBeingLabel"] = "Благополучие: ";
						FavCimsLang.rus["HappinessLabel"] = "Счастье : ";
						FavCimsLang.rus["Wealth_Label"] = "Благосостояние";
						FavCimsLang.rus["Health_Level_VerySick_Male"] = "Тяжело болен";
						FavCimsLang.rus["Health_Level_Sick_Male"] = "Болен";
						FavCimsLang.rus["Health_Level_PoorHealth_Male"] = "Хворает";
						FavCimsLang.rus["Health_Level_Healthy_Male"] = "В норме";
						FavCimsLang.rus["Health_Level_VeryHealthy_Male"] = "Здоров";
						FavCimsLang.rus["Health_Level_ExcellentHealth_Male"] = "До безобразия здоров";
						FavCimsLang.rus["Health_Level_VerySick_Female"] = "Тяжело больна";
						FavCimsLang.rus["Health_Level_Sick_Female"] = "Больна";
						FavCimsLang.rus["Health_Level_PoorHealth_Female"] = "Хворает";
						FavCimsLang.rus["Health_Level_Healthy_Female"] = "В норме";
						FavCimsLang.rus["Health_Level_VeryHealthy_Female"] = "Здорова";
						FavCimsLang.rus["Health_Level_ExcellentHealth_Female"] = "До неприличия здорова";
						FavCimsLang.rus["District_Label"] = "Район: ";
						FavCimsLang.rus["District_Label_tooltip"] = "Сейчас в этом районе";
						FavCimsLang.rus["Citizen_Details_NoUnit"] = "Житель умер или бомж";
						FavCimsLang.rus["Citizen_wait_hearse"] = "Ждет катафалк";
						FavCimsLang.rus["Citizen_on_hearse"] = "В катафалке";
						FavCimsLang.rus["Citizen_hisfuneral"] = "Похороны";
						FavCimsLang.rus["Citizen_buried"] = "Погребен(а)";
						FavCimsLang.rus["Citizen_Tourist_tooltip"] = "Этот турист посещает ваш город";
						FavCimsLang.rus["View_PassengersList"] = "Просмотр пассажиров";
						FavCimsLang.rus["View_NoPassengers"] = "Пассажиров нет";
						FavCimsLang.rus["Vehicle_Passengers"] = "Пассажиры в салоне";
						FavCimsLang.rus["Vehicle_DriverIconText"] = "Водитель";
						FavCimsLang.rus["Vehicle_PasssengerIconText"] = "Пассажиры";
						FavCimsLang.rus["Citizens_HouseHolds"] = "Просмотр жильцов";
						FavCimsLang.rus["Citizens_HouseHoldsTitle"] = "Жильцы";
						FavCimsLang.rus["CitizenOnBuilding"] = "Список кадров и гостей";
						FavCimsLang.rus["CitizenOnBuildingTitle"] = "Сотрудники и Гости";
						FavCimsLang.rus["OnBuilding_Residential"] = "Квартира ";
						FavCimsLang.rus["View_List"] = "Просмотр ";
						FavCimsLang.rus["OnBuilding_Guests"] = "Посетители";
						FavCimsLang.rus["OnBuilding_Workers"] = "Сотрудники";
						FavCimsLang.rus["WorkersOnBuilding"] = "Список сотрудников";
						FavCimsLang.rus["OnBuilding_NoWorkers"] = "На работе никого";
						FavCimsLang.rus["OnBuilding_NoGuests"] = "Посетителей нет";
						FavCimsLang.rus["BuildingIsEmpty"] = "Жителей/работников нет";
						FavCimsLang.rus["OnBuilding_TotalWorkers"] = "Всего :";
						FavCimsLang.rus["Buildings_Type_CommercialEco"] = "Коммер. здание (Экология)";
						FavCimsLang.rus["Buildings_Type_CommercialLeisure"] = "Коммер. здание (Досуг и отдых)";
						FavCimsLang.rus["Buildings_Type_CommercialTourist"] = "Коммер. здание (Туризм)";
						FavCimsLang.rus["Citizen_Arrested"] = "This Citizen is in Jail!";
						FavCimsLang.rus["Transported_to_Prison"] = "Transported to Prison";
						FavCimsLang.rus["Jailed_into"] = "Jailed into ";
						FavCimsLang.rus["Citizen_Under_Arrest"] = "Citizens under arrest";
						FavCimsLang.rus["OnBuilding_noArrested"] = "Nobody jailed here";
						FavCimsLang.rus["OnPolice_Building_Service"] = "Guards and Prisoners";
						FavCimsLang.rus["OnEducation_Building_Service"] = "Teachers and Students";
						FavCimsLang.rus["OnMedical_Building_Service"] = "Doctors and Patients";
						FavCimsLang.rus["Citizen_at_School"] = "Students at school";
						FavCimsLang.rus["Citizen_on_Clinic"] = "Patients being treated";
						return FavCimsLang.rus[index];
					}
					FavCimsLang.en = new Dictionary<string, string>();
					FavCimsLang.en["FavCimsButton_tooltip"] = "My Favorite Cims";
					FavCimsLang.en["FavCimsBCMenuButton_text"] = "Citizens";
					FavCimsLang.en["FavCimsBCMenuButton_tooltip"] = "Followed People";
					FavCimsLang.en["FavCimsBBMenuButton_text"] = "Buildings";
					FavCimsLang.en["FavCimsBBMenuButton_tooltip"] = "Favorite Buildings";
					FavCimsLang.en["FavCimsBSMenuButton_text"] = "Stats";
					FavCimsLang.en["FavCimsBSMenuButton_tooltip"] = "Info and Stats";
					FavCimsLang.en["FavStarButton_enable_tooltip"] = "Click here to add to Favorites!";
					FavCimsLang.en["FavStarButton_disable_tooltip"] = "Click here to remove from Favorites :(";
					FavCimsLang.en["FavCimsHappinesColText_text"] = "Status";
					FavCimsLang.en["FavCimsHappinesColText_tooltip"] = "Citizen Happiness";
					FavCimsLang.en["FavCimsNameColText_text"] = "Citizen Name";
					FavCimsLang.en["FavCimsNameColText_tooltip"] = "Citizen Name";
					FavCimsLang.en["FavCimsEduColText_text"] = "Education";
					FavCimsLang.en["FavCimsEduColText_tooltip"] = "Citizen Education Level";
					FavCimsLang.en["FavCimsWorkingPlaceColText_text"] = "Occupation";
					FavCimsLang.en["FavCimsWorkingPlaceColText_tooltip"] = "Place where the Citizen Works or Study";
					FavCimsLang.en["FavCimsAgePhaseColText_text"] = "Age Phase";
					FavCimsLang.en["FavCimsAgePhaseColText_tooltip"] = "Citizen life Age Phase";
					FavCimsLang.en["FavCimsAgeColText_text"] = "Age";
					FavCimsLang.en["FavCimsAgeColText_tooltip"] = "Citizen Age";
					FavCimsLang.en["FavCimsHomeColText_text"] = "Citizen Home";
					FavCimsLang.en["FavCimsHomeColText_tooltip"] = "Citizen Living in this House";
					FavCimsLang.en["FavCimsLastActColText_text"] = "Last Activity";
					FavCimsLang.en["FavCimsLastActColText_tooltip"] = "What the Citizen is doing at the moment";
					FavCimsLang.en["FavCimsCloseButtonCol_text"] = "Close";
					FavCimsLang.en["FavCimsCloseButtonCol_tooltip"] = "Click on close button for remove citizen from favorites :(";
					FavCimsLang.en["Male"] = "Male";
					FavCimsLang.en["Female"] = "Female";
					FavCimsLang.en["AgePhase_Child_Male"] = "Child";
					FavCimsLang.en["AgePhase_Teen_Male"] = "Boy";
					FavCimsLang.en["AgePhase_Young_Male"] = "Young Man";
					FavCimsLang.en["AgePhase_Adult_Male"] = "Man";
					FavCimsLang.en["AgePhase_Senior_Male"] = "Old Man";
					FavCimsLang.en["Education_Uneducated_Male"] = "Uneducated";
					FavCimsLang.en["Education_OneSchool_Male"] = "Educated";
					FavCimsLang.en["Education_TwoSchools_Male"] = "Well Educated";
					FavCimsLang.en["Education_ThreeSchools_Male"] = "Highly Educated";
					FavCimsLang.en["AgePhase_Child_Female"] = "Child";
					FavCimsLang.en["AgePhase_Teen_Female"] = "Girl";
					FavCimsLang.en["AgePhase_Young_Female"] = "Young Woman";
					FavCimsLang.en["AgePhase_Adult_Female"] = "Woman";
					FavCimsLang.en["AgePhase_Senior_Female"] = "Old Woman";
					FavCimsLang.en["Education_Uneducated_Female"] = "Uneducated";
					FavCimsLang.en["Education_OneSchool_Female"] = "Educated";
					FavCimsLang.en["Education_TwoSchools_Female"] = "Well Educated";
					FavCimsLang.en["Education_ThreeSchools_Female"] = "Highly Educated";
					FavCimsLang.en["AgePhaseDead_Male"] = "Dead";
					FavCimsLang.en["AgePhaseDead_Female"] = "Dead";
					FavCimsLang.en["People_Life_Status_Alive"] = "Citizen is alive";
					FavCimsLang.en["People_Life_Status_Dead"] = "Citizen is dead";
					FavCimsLang.en["People_Life_Status_Dead_date"] = "on this date";
					FavCimsLang.en["People_Life_Status_Dead_time"] = "at time";
					FavCimsLang.en["NotificationIconVeryUnhappy"] = "Very Unhappy";
					FavCimsLang.en["NotificationIconUnhappy"] = "Unhappy";
					FavCimsLang.en["NotificationIconHappy"] = "Happy";
					FavCimsLang.en["NotificationIconVeryHappy"] = "Very Happy";
					FavCimsLang.en["NotificationIconExtremelyHappy"] = "Extremely Happy";
					FavCimsLang.en["time_format"] = "mm-dd-yyyy";
					FavCimsLang.en["People_Life_Status_IsGone"] = "Citizen is gone away from the city";
					FavCimsLang.en["Citizen_HomeLess"] = "Homeless";
					FavCimsLang.en["Citizen_HomeLess_tooltip"] = "Citizen has no home";
					FavCimsLang.en["HomeOutsideTheCity"] = "Far far away";
					FavCimsLang.en["Home_Location_Dead"] = "At Cemetery";
					FavCimsLang.en["Citizen_Retired"] = "Retired";
					FavCimsLang.en["Citizen_Retired_tooltip"] = "Citizen retired from work";
					FavCimsLang.en["Unemployed_tooltip"] = "Citizen has much free time at the moment...";
					FavCimsLang.en["Government_job"] = "Government Building";
					FavCimsLang.en["Electricity_job"] = "Electricity Plant";
					FavCimsLang.en["Water_job"] = "Water Plant";
					FavCimsLang.en["Generic_job_place"] = "Citizen Works in this building";
					FavCimsLang.en["Vehicle_on_foot"] = "Citizen walking on foot";
					FavCimsLang.en["Citizen_Details"] = "Citizen Detail";
					FavCimsLang.en["Citizen_Details_fullTemplate"] = "Too many Family Windows opened, close one before open another";
					FavCimsLang.en["Status_static_label"] = "Status : ";
					FavCimsLang.en["Citizen_Family_unit"] = "Family";
					FavCimsLang.en["NowInThisDistrict"] = "In this moment is in District: ";
					FavCimsLang.en["DistrictLabel"] = "District: ";
					FavCimsLang.en["DistrictNameNoDistrict"] = "None";
					FavCimsLang.en["Citizen_Details_No_Partner"] = "No Partner";
					FavCimsLang.en["Citizen_Details_No_Childs"] = "No Childs";
					FavCimsLang.en["Right_click_to_swith_tooltip"] = "Right Click to Switch Citizen";
					FavCimsLang.en["Home_Bubble_panel_Label"] = "Home : ";
					FavCimsLang.en["Low_Wealth_Male"] = "Poor";
					FavCimsLang.en["Mid_Wealth_Male"] = "Well-off";
					FavCimsLang.en["High_Wealth_Male"] = "Rich";
					FavCimsLang.en["Low_Wealth_Female"] = "Poor";
					FavCimsLang.en["Mid_Wealth_Female"] = "Well-off";
					FavCimsLang.en["High_Wealth_Female"] = "Rich";
					FavCimsLang.en["WellBeingLabel"] = "Wellbeing: ";
					FavCimsLang.en["HappinessLabel"] = "Happiness : ";
					FavCimsLang.en["Wealth_Label"] = "Wealth";
					FavCimsLang.en["Health_Level_VerySick_Male"] = "Very Sick";
					FavCimsLang.en["Health_Level_Sick_Male"] = "Sick";
					FavCimsLang.en["Health_Level_PoorHealth_Male"] = "Poor Health";
					FavCimsLang.en["Health_Level_Healthy_Male"] = "Healthy";
					FavCimsLang.en["Health_Level_VeryHealthy_Male"] = "Very Healthy";
					FavCimsLang.en["Health_Level_ExcellentHealth_Male"] = "Excellent Health";
					FavCimsLang.en["Health_Level_VerySick_Female"] = "Very Sick";
					FavCimsLang.en["Health_Level_Sick_Female"] = "Sick";
					FavCimsLang.en["Health_Level_PoorHealth_Female"] = "Poor Health";
					FavCimsLang.en["Health_Level_Healthy_Female"] = "Healthy";
					FavCimsLang.en["Health_Level_VeryHealthy_Female"] = "Very Healthy";
					FavCimsLang.en["Health_Level_ExcellentHealth_Female"] = "Excellent Health";
					FavCimsLang.en["District_Label"] = "District: ";
					FavCimsLang.en["District_Label_tooltip"] = "In this District at the moment";
					FavCimsLang.en["Citizen_Details_NoUnit"] = "Citizen is dead or homeless";
					FavCimsLang.en["Citizen_wait_hearse"] = "Waiting for funeral car";
					FavCimsLang.en["Citizen_on_hearse"] = "On funeral car";
					FavCimsLang.en["Citizen_hisfuneral"] = "Funeral ceremony";
					FavCimsLang.en["Citizen_buried"] = "Six Feet Under";
					FavCimsLang.en["Citizen_Tourist_tooltip"] = "This citizen is visiting our City";
					FavCimsLang.en["View_PassengersList"] = "View passengers list";
					FavCimsLang.en["View_NoPassengers"] = "No passengers";
					FavCimsLang.en["Vehicle_Passengers"] = "Passengers on board";
					FavCimsLang.en["Vehicle_DriverIconText"] = "Vehicle Driver";
					FavCimsLang.en["Vehicle_PasssengerIconText"] = "Passengers";
					FavCimsLang.en["Citizens_HouseHolds"] = "View Residents";
					FavCimsLang.en["Citizens_HouseHoldsTitle"] = "Residents";
					FavCimsLang.en["CitizenOnBuilding"] = "Employees and Guests List";
					FavCimsLang.en["CitizenOnBuildingTitle"] = "Employees and Guests";
					FavCimsLang.en["OnBuilding_Residential"] = "Apartment ";
					FavCimsLang.en["View_List"] = "View ";
					FavCimsLang.en["OnBuilding_Guests"] = "Guests";
					FavCimsLang.en["OnBuilding_Workers"] = "Employees at work";
					FavCimsLang.en["WorkersOnBuilding"] = "List of employees at work";
					FavCimsLang.en["OnBuilding_NoWorkers"] = "Nobody at work";
					FavCimsLang.en["OnBuilding_NoGuests"] = "No guests inside";
					FavCimsLang.en["BuildingIsEmpty"] = "Nobody works or lives here";
					FavCimsLang.en["OnBuilding_TotalWorkers"] = "Tot :";
					FavCimsLang.en["Buildings_Type_CommercialEco"] = "Ecologic Commercial Building";
					FavCimsLang.en["Buildings_Type_CommercialLeisure"] = "Leisure Commercial Building";
					FavCimsLang.en["Buildings_Type_CommercialTourist"] = "Tourism Commercial Building";
					FavCimsLang.en["Citizen_Arrested"] = "This Citizen is in Jail!";
					FavCimsLang.en["Transported_to_Prison"] = "Transported to Prison";
					FavCimsLang.en["Jailed_into"] = "Jailed into ";
					FavCimsLang.en["Citizen_Under_Arrest"] = "Citizens under arrest";
					FavCimsLang.en["OnBuilding_noArrested"] = "Nobody jailed here";
					FavCimsLang.en["OnPolice_Building_Service"] = "Guards and Prisoners";
					FavCimsLang.en["OnEducation_Building_Service"] = "Teachers and Students";
					FavCimsLang.en["OnMedical_Building_Service"] = "Doctors and Patients";
					FavCimsLang.en["Citizen_at_School"] = "Students at school";
					FavCimsLang.en["Citizen_on_Clinic"] = "Patients being treated";
					return FavCimsLang.en[index];
				}
				catch
				{
					return "language Error";
				}
			}
			bool flag5 = FavCimsLang.GameLanguage == "(ITALIAN)";
			string text;
			if (flag5)
			{
				text = FavCimsLang.it[index];
			}
			else
			{
				bool flag6 = FavCimsLang.GameLanguage == "(DUTCH)";
				if (flag6)
				{
					text = FavCimsLang.nl[index];
				}
				else
				{
					bool flag7 = FavCimsLang.GameLanguage == "(RUSSIAN)";
					if (flag7)
					{
						text = FavCimsLang.rus[index];
					}
					else
					{
						text = FavCimsLang.en[index];
					}
				}
			}
			return text;
		}
	}
}
